name: Android CI

on:
  pull_request:
    branches: [ master, main, develop, 'release/**' ]
    types: [ opened, synchronize ]

jobs:
  assemble_modules:
    name: Assemble modules
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Assemble app debug APK
        run: bash ./gradlew assembleDebug

  code_quality_analysis:
    name: Check code quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Misspelling on detekt + ktlint
        run: bash ./gradlew detekt --stacktrace --continue
      - name: Run unit tests and check coverage
        run: bash ./gradlew jacocoCoverageVerification --stacktrace --continue
